sequenceDiagram
  participant participant_createDockerComposeCliControlPlane as createDockerComposeCliControlPlane
  participant participant_createInfraAdapter as createInfraAdapter
  participant participant_createLocalDockerComposeSessionResolver as createLocalDockerComposeSessionResolver
  participant participant_createSubprocessDockerComposeCommandRunner as createSubprocessDockerComposeCommandRunner
  participant_createInfraAdapter->>participant_createDockerComposeCliControlPlane: createDockerComposeCliControlPlane()
  participant_createDockerComposeCliControlPlane->>participant_createLocalDockerComposeSessionResolver: createLocalDockerComposeSessionResolver()
  participant_createLocalDockerComposeSessionResolver->>participant_createSubprocessDockerComposeCommandRunner: createSubprocessDockerComposeCommandRunner()
  participant_createSubprocessDockerComposeCommandRunner-->>participant_createLocalDockerComposeSessionResolver: return
  participant_createLocalDockerComposeSessionResolver-->>participant_createDockerComposeCliControlPlane: return
  participant_createDockerComposeCliControlPlane-->>participant_createInfraAdapter: return
