sequenceDiagram
  participant participant_createLocalDockerComposeSessionResolver as createLocalDockerComposeSessionResolver
  participant participant_createSubprocessDockerComposeCommandRunner as createSubprocessDockerComposeCommandRunner
  participant_createLocalDockerComposeSessionResolver->>participant_createSubprocessDockerComposeCommandRunner: createSubprocessDockerComposeCommandRunner()
  participant_createSubprocessDockerComposeCommandRunner-->>participant_createLocalDockerComposeSessionResolver: return
